### PR TITLE
update initialopen ids on props change

### PR DESCRIPTION
**Pull request by broncha**
When you change the initialOpen props, it has no effect right now. I needed this so I could track and change open nodes from my redux state.

### CODE REVIEW

**Comment by minop1205** [comment]
@broncha 
Thanks for the PR!

The code is fine. But the name of the prop is `initialOpen`, so I think it needs to be explained.

Can you please add to the API description in the README that if the prop is updated, the open state of the tree is also reset?

image

**Comment by broncha** [comment]
@minop1205 updated readme

**Comment by minop1205** [comment]
@broncha 
Confirmed.
Thank you!

**Comment by broncha** [comment]
@minop1205 you plan on a new release soon?

**Comment by minop1205** [comment]
@broncha I have just published v2.0.2.
The initialOpen fix is also included in this version.

**Comment by broncha** [comment]
@minop1205 Thanks a lot!

**Pull request merged**
